name: Update homebrew formula

on:
  workflow_dispatch:
    inputs:
      formula:
        required: true
        description: Formula to update
      source_repository:
        required: true
        description: Repository with source code
      tag_name:
        required: true
        description: Name of release tag

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Formula
      run: python3 scripts/update_formula.py
      env:
        INPUT_TAG_NAME: ${{ github.event.inputs.tag_name }}
        INPUT_FORMULA: ${{ github.event.inputs.formula }}
        INPUT_SOURCE_REPOSITORY: ${{ github.event.inputs.source_repository }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: Update port ${{ github.event.inputs.port }} to ${{ github.event.inputs.source_repository }} ${{ github.event.inputs.tag_name }}
        token: ${{ secrets.BOT_GITHUB_TOKEN }}
    
      

      
      
  